### GET
GET http://localhost:9001/document/v1/stock/
Accept: application/json

### POST
POST http://localhost:9001/document/v1/stock/
Content-Type: application/json

{
  "name": "content",
  "price": 1,
  "amount": 2,
  "description": 3,
  "status": true
}