{
 "title": "test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "count 200",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=\"SUCCESS\", uri!=\"/actuator/prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket[1m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"}) by (instance)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"}) by (instance)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes) by (instance)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes) by (instance)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes) by (instance)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "r2dbc pending",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(r2dbc_pool_acquired_connections[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}