###
POST http://localhost:8081/api/v1/stock
Content-Type: application/json

{
  "name": "TEST",
  "price": "10.98",
  "description": "APL"
}

### find by symbol
GET http://localhost:8081/api/v1/stock?symbol=TEST
Content-Type: application/json

### find all
GET  http://localhost:8081/api/v1/stocks